FROM padmec/elliptic:1.0

RUN pip install --upgrade pip
RUN pip install ipython
RUN pip install pyyaml
RUN pip install numba
RUN pip install scipy
RUN pip install XlsxWriter==1.1.2
RUN pip install hdmedians
RUN pip install pytest
WORKDIR $HOME
